services:
  postgres:
    image: postgres:17
    container_name: communities_postgres
    environment:
      POSTGRES_DB: communities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./compose/init-uuid.sql:/docker-entrypoint-initdb.d/01-init-uuid.sql
    restart: unless-stopped

volumes:
  postgres_data:
