{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "message.fullname" . }}-db
  labels:
    {{- include "message.labels" . | nindent 4 }}
type: Opaque
data:
  uri: {{ required "database.uri is required when database.existingSecret is not set" .Values.database.uri | b64enc | quote }}
{{- end }}
---
{{- if not .Values.jwt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "message.fullname" . }}-jwt
  labels:
    {{- include "message.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.jwt.secretKey }}: {{ required "jwt secret value is required when jwt.existingSecret is not set" .Values.jwt.secret | b64enc | quote }}
{{- end }}
---
{{- if not .Values.rabbitmq.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "message.fullname" . }}-rabbitmq
  labels:
    {{- include "message.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ required "rabbitmq.url is required when rabbitmq.existingSecret is not set" .Values.rabbitmq.url | b64enc | quote }}
{{- end }}
