apiVersion: v1
kind: Service
metadata:
  name: {{ include "message.fullname" . }}
  labels:
    {{- include "message.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "message.selectorLabels" . | nindent 4 }}
